name: spiceflow-mainnet
api_config:
  host: "0.0.0.0"
  port: 3000
  authentication_username: ${RRELAYER_AUTH_USERNAME}
  authentication_password: ${RRELAYER_AUTH_PASSWORD}

signing_provider:
  private_keys:
    - raw: ${RRELAYER_PRIVATE_KEY}

networks:
  - name: ethereum
    chain_id: 1
    provider_urls:
      - https://eth-mainnet.g.alchemy.com/v2/7SgOekVydB9TOyNk3NKj8
    block_explorer_url: https://etherscan.io
    enable_sending_blobs: true
    allowed_random_relayers: "*"

  - name: citrea_mainnet
    chain_id: 4114
    provider_urls:
      - https://citrea-mainnet.g.alchemy.com/v2/7SgOekVydB9TOyNk3NKj8
    block_explorer_url: https://explorer.mainnet.citrea.xyz
    enable_sending_blobs: true
    allowed_random_relayers: "*"

  - name: arbitrum_one
    chain_id: 42161
    provider_urls:
      - https://arb-mainnet.g.alchemy.com/v2/7SgOekVydB9TOyNk3NKj8
    block_explorer_url: https://arbiscan.io
    enable_sending_blobs: true
    allowed_random_relayers: "*"

  - name: base_mainnet
    chain_id: 8453
    provider_urls:
      - https://base-mainnet.g.alchemy.com/v2/7SgOekVydB9TOyNk3NKj8
    block_explorer_url: https://basescan.org
    enable_sending_blobs: true
    allowed_random_relayers: "*"
